### ISSUE TITLE
character name を変えられるようにする

### ISSUE THREAD

**Issue by KKawamura1** [aqla114/arian-battle-table#45]
コピー機能を使ってコピーした character の名前が変えられず、不便。

**Comment by aqla114** [comment]
**分かるオブザイヤー2020**

**Comment by aqla114** [comment]
ちなみに真面目な話をします（ほぼ自分向けメモ）。

まず、何故 character の名前を固定しているかというと、 React で複数同じタグを子に持つ場合にそれぞれの要素にユニークな key を与えなくちゃいけなくて、現状それをキャラクター名にしているからです。 https://ja.reactjs.org/docs/lists-and-keys.html
厳密には、重複しないようにキャラクター名を更新できるようにすればいいのですが、面倒くさくて実装してません。

他の数値入力の部分と同じような感じで、 `onBlur` のタイミングで redux の action が走るようにして、そのタイミングで他と重複しないように validation をかければシュッと実装できそう。たぶん。

**Comment by KKawamura1** [comment]
名前を重複しないように頑張るより、一意な id を発行してそれを使ったほうが親切なように思えます。ので、そういう感じの実装をしてみました。
